{{ if .Values.global.gloo.enabled }}
{{- $internal := .Values.virtualServices.httpInternal }}
{{- $spec := .Values.virtualServices.http }}
{{- $port := $spec.port | default "80" }}
{{ if or (not $spec.enabled) ($spec.redirect) }}
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: {{ $internal.name }}
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- range $key, $value := $internal.labels}}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  displayName: http-internal
  virtualHost:
    domains:
    - internal.{{ .Release.Namespace }}
    routes:
    - matchers:
      - prefix: '/'
      delegateAction:
        selector:
          labels:
            app: tidepool
          namespaces:
            - {{ $.Release.Namespace }}

{{- end }}
{{- end }}
