{{ if .Values.aws.enabled -}}
---
apiVersion: v1
{{ with .Values.aws.data_ }}
data:
  AWSAccessKeyID: {{ .AWSAccessKeyID | default "" | b64enc | quote }}
  AWSSecretAccessKey: {{ .AWSSecretAccessKey | default "" | b64enc | quote }}
{{- end }}
kind: Secret
metadata:
  name: aws
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
