{{ if .Values.dexcom.enabled -}}
---
apiVersion: v1
{{ with .Values.dexcom.data_ -}}
data:
  ClientId: {{ .ClientId | default "" | b64enc | quote }}
  ClientSecret: {{ .ClientSecret | default "" | b64enc | quote }}
  StateSalt: {{ .StateSalt | default "" | b64enc | quote }}
{{- end }}
kind: Secret
metadata:
  name: dexcom
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
