{{ if or .Values.kissmetrics.enabled .Values.global.secret.templated -}}
---
apiVersion: v1
{{ with .Values.kissmetrics.data_ -}}
data:
  APIKey: {{ .APIKey | default "" | b64enc | quote  }}
  Token: {{ .Token | default "" | b64enc  | quote }}
  UCSFAPIKey: {{ .UCSFAPIKey | default "" | b64enc | quote }}
  UCSFWhitelist: {{ .UCSFWhitelist | default "" | b64enc | quote }}
{{- end }}
kind: Secret
metadata:
  name: kissmetrics
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
