{{ if or .Values.userdata.enabled .Values.global.secret.generated -}}
---
apiVersion: v1
{{ with .Values.userdata.data_ -}}
data:
  GroupIdEncryptionKey: {{ .ServiceAuth | default (randAlphaNum 40) | b64enc | quote }}
  UserIdSalt: {{ .UserIdSalt | default (randAlphaNum 40) | b64enc | quote  }}
  UserPasswordSalt: {{ .PasswordSalt | default (randAlphaNum 40) | b64enc | quote }}
{{- end }}
kind: Secret
metadata:
  name: userdata
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
