{{ if .Values.secret.enabled -}}
---
apiVersion: v1
{{- with .Values.secret.data_ }}
data:
  LibreViewUsername: {{ .LibreViewUsername | b64enc | quote }}
  LibreViewPassword: {{ .LibreViewPassword | b64enc | quote }}
{{- end }}
kind: Secret
metadata:
  name: jellyfish
  namespace: {{ .Release.Namespace }}
  labels:
    app: jellyfish
type: Opaque
{{- end }}
