secret:
  # -- whether to create mongo secret
  enabled: false
  data_:
    # -- plaintext Mongo DB scheme, either `mongodb` or `mongodb+srv`
    Scheme: ""
    # -- plaintext comma-separated list of Mongo `host[:port]` addresses
    Addresses: ""
    # -- plaintext, If non-empty, Mongo username
    Username: ""
    # -- plaintext Mongo password
    Password: ""
    # -- plaintext Mongo database name
    Database: ""
    # -- plaintext, If true, use SSL on Mongo connection
    Tls: ""
    # -- plaintext additional Mongo connection params
    OptParams: ""
