{{ if .Values.global.gloo.enabled }}
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: prescription
  namespace: {{ .Release.Namespace }}
  labels:
    namespace: {{ .Release.Namespace }}
    app: tidepool
spec:
  routes:
  - matchers:
    - methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      prefix: /v1/prescriptions
    routeAction:
      single:
        upstream:
          name: prescription
  - matchers:
    - methods:
      - GET
      regex: /v1/users/[^/]+/prescriptions
    routeAction:
      single:
        upstream:
          name: prescription
{{- end }}
