# --  whether to enable service
enabled: true
configmap:
  # -- whether to generate configmap
  enabled: false
deployment:
  # -- docker image to deploy
  image: tidepool/jellyfish:master-latest
  # -- number of replicas to deploy
  replicas: 1
store:
  # -- base name of mongo database to use
  database: data
  # -- prefix to apply to mongo database name
  prefix: ""
serviceAccount:
  # -- whether to create a service account
  create: false

# -- memory and cpu resources for pods
resources: {}
# -- security context for each pod in deployment
podSecurityContext: {}
# -- annotations for each pod in deployment
podAnnotations: {}
securityContext: {}
mongo:
  # -- name of the secret containing the credentials of the mongo database to use
  secretName: mongo
# -- node selector configuration
nodeSelector: {}
# -- tolerations
tolerations: []
# -- affinity
affinity: {}
