deployment:
  # -- tidewhisperer Docker image
  image: tidepool/tide-whisperer:master-latest
  # -- number of replicas
  replicas: 1
serviceMonitor:
  # -- whether to generate a prometheus-operator service monitor
  enabled: false
# -- memory and cpu resources for pods
resources: {}
# -- security context for each pod in deployment
podSecurityContext: {}
# -- annotations for each pod in deployment
podAnnotations: {}
securityContext: {}
mongo:
  # -- name of the secret containing the credentials of the mongo database to use
  secretName: mongo
# -- node selector configuration
nodeSelector: {}
# -- tolerations
tolerations: []
# -- affinity
affinity: {}
