{{ if .Values.global.gloo.enabled }}
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: messageapi
  namespace: {{ .Release.Namespace }}
spec:
  kube:
    serviceName: message-api
    serviceNamespace: {{ .Release.Namespace }}
    servicePort: {{ .Values.global.ports.messageapi }}
{{- end }}
