apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
    helm.sh/chart: {{ include "charts.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "charts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: mongodb
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - name: "{{.Values.port}}"
    port: {{.Values.port}}
    targetPort: {{.Values.port}}
  selector:
    app: mongodb
    app.kubernetes.io/name: {{ include "charts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
