{{ if .Values.global.gloo.enabled }}
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: seagull
  namespace: {{ .Release.Namespace }}
spec:
  kube:
    serviceName: seagull
    serviceNamespace: {{ .Release.Namespace }}
    servicePort: {{ .Values.global.ports.seagull }}
{{- end }}
