apiVersion: v2
description: A Helm chart to use Gloo for Tidepool ingress 
name: gloo
version: 0.1.0
appVersion: 1.3.2
icon: https://www.tidepool.org/static/media/tidepool-t-logo.41feef82.png
home: https://github.com/line-studio/tidepool-charts
