{{ if or .Values.server.enabled .Values.global.secret.generated -}}
---
apiVersion: v1
data:
  ServiceAuth: {{ .Values.server.data_.ServiceAuth | default (randAlphaNum 40) | b64enc | quote }}
kind: Secret
metadata:
  name: server
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
