{{ if .Values.token-signing-key.enabled -}}
---
apiVersion: v1
{{ with .Values.token-signing-key.data_ -}}
data:
  public: {{ .public | default "" | b64enc | quote }}
  private: {{ .private | default "" | b64enc | quote }}
{{- end }}
kind: Secret
metadata:
  name: token-signing-key
  namespace: {{ .Release.Namespace }}
  labels:
    app: token-signing-key
type: Opaque
{{- end }}
