---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blip
  name: blip
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - name: "http"
    port: {{ .Values.global.ports.blip }}
    targetPort: {{ .Values.global.ports.blip }}
{{ range $key, $port := .Values.global.ports.viz }}
  - name: 'http-viz-{{ $key }}'
    port: {{ $port }}
    targetPort: {{ $port }}
{{- end }}
  selector:
    app: blip
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
